### ISSUE TITLE
Explore multiprobe for L1, Hamming, Jaccard

### ISSUE THREAD

**Issue by alexklibisz** [alexklibisz/elastiknn#1]
This should come after implementing regular LSH for all of the similarities.

I don't think the multiprobe paradigm makes sense for Hamming and Jaccard. It might for L1 but I haven't done a lot of research on that. I know it makes sense for L2, since that's what the original paper did, and I'm fairly certain I've seen it described for cosine similarity.

**Comment by grzegrzolkapawel** [comment]
I agree

**Comment by alexklibisz** [comment]
Your Message to Comment
