### ISSUE TITLE
Error at index creation

### ISSUE THREAD

**Issue by BeardyBear** [alexklibisz/elastiknn#101]
Hi,

I am using index creation API with following payload:

```
{
	"mappings": {
		"properties": {
			"my_vec": {
				"type": "elastiknn_dense_float_vector",
				"elastiknn": {
					"dims": 256,
					"similarity": "l2",
					"model": "lsh"
				}
			}
		}
	}
}
```

I get the following error:

```
{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Attempt to decode value on failed cursor: DownField(bands)"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [_doc]: Attempt to decode value on failed cursor: DownField(bands)","caused_by":{"type":"","reason":"Attempt to decode value on failed cursor: DownField(bands)"}},"status":400}
```

Not sure what I am missing and would appreciate any help a lot.

**Comment by alexklibisz** [comment]
Hi, the error message is a bit verbose, but it's saying you are missing the "bands" field.
That's part of the L2-lsh mapping, which is fully outlined here: http://elastiknn.klibisz.com/api/#l2-lsh-mapping

**Comment by BeardyBear** [comment]
Thank you very much!

Guess I was just sleepy :)

**Comment by alexklibisz** [comment]
No problem. Let me know if you have any other questions.
