### ISSUE TITLE
Build for multiple elasticsearch versions

### ISSUE THREAD

**Issue by alexklibisz** [alexklibisz/elastiknn#120]

**Comment by iguy0** [comment]
Hi,

I understand the need to go back some versions is present, however for the developer, moving forward is the way to go. Plus managing packages and issues related to backporting might hinder the time spent moving forward. My suggestion is to provide general instructions on how to backport to a subversion(7.9.3 -> 7.9.1), but within a major version(7.9.x or 7.x) as well as compiling instructions.

Thanks

**Comment by alexklibisz** [comment]
@iguy0 Yeah that's what I'm leaning towards for sure. I experimented a bit with keeping multiple versions in master at the same time, but it's really tricky because the ES internals can change between minor version bumps.

**Comment by alexklibisz** [comment]
Giving up on this. Very tricky and so far nobody has asked for it.
