### ISSUE TITLE
elastiknn_dense_float_vector field in "exist" clause

### ISSUE THREAD

**Issue by ejackson-eb** [alexklibisz/elastiknn#174]
I have created a field of type elastiknn_dense_float_vector, but I don't seem to be able to query for it in all the ways I expect.  I would like, for example, to be able to count how many documents have this field like so:

GET my_index/_count
{
  "query": {
      "exists":{
         "field":"my_field"
      }
    }
}

This does not seem to work.

**Comment by alexklibisz** [comment]
Hmm, it seems to work for me. I created an index with 99 vectors and ran these requests:

```
alex@xps:~/Documents/dev/elastiknn$ curl localhost:9200/issue-174/_count
{"count":99,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0}}alex@xps:~/Documents/dev/elastiknn$ curl localhost:9200/issue-174/_mapping?pretty
{
  "issue-174" : {
    "mappings" : {
      "properties" : {
        "id" : {
          "type" : "keyword",
          "store" : true
        },
        "vec" : {
          "type" : "elastiknn_dense_float_vector",
          "similarity" : "boolean",
          "elastiknn" : {
            "model" : "lsh",
            "similarity" : "l2",
            "dims" : 128,
            "L" : 50,
            "k" : 1,
            "w" : 2
          }
        }
      }
    }
  }
}
alex@xps:~/Documents/dev/elastiknn$ curl localhost:9200/issue-174/_count?pretty
{
  "count" : 99,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  }
}
alex@xps:~/Documents/dev/elastiknn$ curl -X GET "localhost:9200/issue-174/_count?pretty" -H 'Content-Type: application/json' -d'
{
  "query" : {
    "exists" : { 
      "field" : "vec" 
    }
  }
}
'
{
  "count" : 99,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  }
}
```

**Comment by alexklibisz** [comment]
Another hmm, it does seem to fail with the exact mapping.

**Comment by alexklibisz** [comment]
@ejackson-eb Can you try again using this build: https://github.com/alexklibisz/elastiknn/releases/download/0.1.0-PRE41-PR175-SNAPSHOT/elastiknn-0.1.0-PRE41-PR175-SNAPSHOT_es7.6.2.zip

**Comment by ejackson-eb** [comment]
Still not working.

**Comment by alexklibisz** [comment]
> Still not working.

Gotcha. Maybe you're trying it without re-indexing the data first? If so, you'll need to re-index the vectors.
Otherwise, maybe you can provide a small repro, either a python script or bash script with curl commands is usually good.

**Comment by ejackson-eb** [comment]
I didn't realize I would need to reindex.  I will try again.

**Comment by alexklibisz** [comment]
> I didn't realize I would need to reindex. I will try again.

no worries, I didn't mention it :). Here's an explanation for why: https://github.com/alexklibisz/elastiknn/pull/175/files#diff-3bd14d078188074c410028847113ceae68865d0ad5b844a27183ef87fbe2fcc3R1

**Comment by ejackson-eb** [comment]
It works after reindexing, thanks!

**Comment by alexklibisz** [comment]
Great. I'll merge and release the fix.
