### ISSUE TITLE
Query by indexed query vector

### ISSUE THREAD

**Issue by techhero-es** [alexklibisz/elastiknn#188]
Hi,

First of all thank you for this great plugin!

I am trying to do a query using an indexed vector but get an error `"Unexpected field: [field]; valid fields: : DownField(vec)"`.

I followed the documentation for the mapping
`{
    "properties": {
        "my_vec": {
            "type": "elastiknn_dense_float_vector",
            "elastiknn": {
                "dims": 100
            }
        }
    }
}
`

and data structure
`
{
    "my_vec": {
        "values": [...]
    }
}
`

Query using a vector works as expected
`{
    "query": {
        "elastiknn_nearest_neighbors": {
            "field": "my_vec",
            "vec": {
              "values": [...]
            },
             "model": "exact",
             "similarity": "l1"
        }
    }
}
`

Query by indexed vector fails with the error mentioned above
`
{
    "query": {
        "elastiknn_nearest_neighbors": {
            "field": "my_vec",
            "vec": {
                "index": "my-index",
                "field": "my_vec",
                "id": 1
            },
             "model": "exact",
             "similarity": "l1"
        }
    }
}
`

What am I doing wrong? The only difference to the example in the documentation is that the indexed vector is in the same index. Is that an issue?

Thank you,

**Comment by alexklibisz** [comment]
I don't see anything obviously wrong with the query.  
The error indicates that JSON parsing fails at some point.
 Can you post more of the stacktrace so I know at what stage in the query lifecycle this error is happening?

**Comment by techhero-es** [comment]
The full error message is
` {
  "error": {
    "root_cause": [
      {
        "type": "",
        "reason": "Unexpected field: [id]; valid fields: : DownField(vec)"
      }
    ],
    "type": "",
    "reason": "Unexpected field: [id]; valid fields: : DownField(vec)"
  },
  "status": 500
}
`

and the log just says
`[2020-10-30T16:34:58,392][WARN ][r.suppressed             ] [Matthiass-MacBook-Pro.local] path: /my-index/_search, params: {index=my-index}
io.circe.DecodingFailure$$anon$2: Unexpected field: [id]; valid fields: : DownField(vec)`

I am using `elastiknn 0.1.0-PRE43_es7.6.2`. I hope this helps. Is there a way to get a full stacktrace?

**Comment by alexklibisz** [comment]
I think this might be more of a CURL and/or http issue.

This might work:

First, use `"id": "1"`, since the id is a string.

Then, use `--data-binary` instead of `-d`.

```
curl -XPOST 'localhost:9200/my-index/_search' -H 'Content-Type: application/json' --data-binary @querybyid.json
```

See [here](https://stackoverflow.com/a/26899363/1695454) for `--data-binary` reasoning.

**Comment by techhero-es** [comment]
It works! Specifying the id as a string did the trick.

Thank you!

**Comment by alexklibisz** [comment]
Great. I'll try to make that more clear in the docs or at least improve the error message.
