### ISSUE TITLE
Old plugin releases get deleted

### ISSUE THREAD

**Issue by averma21** [alexklibisz/elastiknn#238]
A few months back I downloaded 7.9.x.x version of elastiknn plugin but now I can't find them in the releases page - https://github.com/alexklibisz/elastiknn/tags

I see that you have mentioned - "For now I’m only releasing the plugin for a single Elasticsearch version. I’d like to eventually come back and implement releases for multiple versions." here - https://elastiknn.com/installation/

The problem with this is that if I don't upgrade to latest version of elasticsearch everytime, I would myself have to keep the older plugin release downloaded somewhere.

Could you please elaborate the reason behind deletion of older versions of the plugin? Would it not make sense to just keep them available for downloads?

**Comment by alexklibisz** [comment]
Hi, they don't actually get deleted. Perhaps it's a bit confusing because I changed the version naming from 0.1.0-pre<N> to <es version>.<N> about a month ago.

If you look at the last 0.1.0 version, it should be for 7.9.3.
