### ISSUE TITLE
Running nearest neighbour query on filtered results using elastic4s client

### ISSUE THREAD

**Issue by iambalajive** [alexklibisz/elastiknn#264]
The scala client doesnt support nearest neighbour queries on filtered results example https://elastiknn.com/api/#common-patterns .

Can you provide some workaround for this

`{
  "size": 10,
  "query": {
    "function_score": {
      "query": {
        "term": { "color": "blue" }                 
      },
      "functions": [                                
        {
          "elastiknn_nearest_neighbors": {           
            "field": "vec",
            "similarity": "angular",
            "model": "exact",
            "vec": {
              "values": [0.1, 0.2, 0.3]
            }
          }
        }
      ]
    }
  }
}`

**Comment by alexklibisz** [comment]
So far I've been constructing a raw JSON string and submitting through the elastic4s `SearchRequesst#source()` method. There are some examples [in this test suite](https://github.com/alexklibisz/elastiknn/blob/657d5de86a371651c5f4aed90c38444389cb9aa2/elastiknn-testing/src/test/scala/com/klibisz/elastiknn/query/FunctionScoreQuerySuite.scala).

You can construct `SearchRequest`s for elastic4s using the methods in [com.klibisz.elastiknn.ElastiknnRequests](https://elastiknn.com/docs/scaladoc/com/klibisz/elastiknn/client/ElastiknnRequests$.html). I don't think it's a good idea to expand the Elastiknn client much further. Instead I think it should just cover the surface area of Elastiknn queries and elastic4s should do the rest.

**Comment by alexklibisz** [comment]
Closing this but feel free to reopen if you have any more questions.
