### ISSUE TITLE
Upgrade scipy dependency to 1.7.0

### ISSUE THREAD

**Issue by priamai** [alexklibisz/elastiknn#280]
Hi there, wonderful project and I became addicted to it.
I use it very well with sklearn pandas to build the transformed dataframes which I then convert into the vector fields.
However sklearn pandas requires scipy-1.7.0 but elasticknn depends on scipy==1.4.1.
It seems to be working just find but would be nice to bump up the dependency if possible.
Cheers!

**Comment by alexklibisz** [comment]
Sounds good. I can do a quick round of python dependency upgrades. That hasn't been done in a while.

**Comment by alexklibisz** [comment]
@priamai There's a snapshot build based on #281 here: https://test.pypi.org/project/elastiknn-client/7.13.2.2.dev968/
Can you try it out and make sure it works as expected? It passes tests, but otherwise I don't actually use the python client for anything interesting.

**Comment by priamai** [comment]
Yes testing this week, cheers!

**Comment by priamai** [comment]
I am doing a large test tonight will feedback in a day or so.
Thanks!

**Comment by priamai** [comment]
So I found an issue but maybe is my interpretation which is wrong.
I reduced it to a simple example:
```

data_binary = array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

eknn = ElastiknnClient(es)

n, dim = data_binary.shape
index = "py-databinary-mapper"
vec_field = "vec"
id_field = "id"
mapping = Mapping.SparseBool(dims=dim)

eknn.es.indices.delete(index, ignore=[400, 404])
eknn.es.indices.refresh()
eknn.es.indices.create(index)
eknn.es.indices.refresh()

m = eknn.put_mapping(index, vec_field, mapping, "id")

vecs = utils.ndarray_to_sparse_bool_vectors(data_binary)

ids = [f"vec-{i}" for i in range(n)]

(n_, errors) = eknn.index(index, vec_field, vecs, id_field, ids, refresh=True)
assert n_ == n
assert len(errors) == 0
```

This fails and no errors are present.
What is strange is the vector field:

```
Vec.SparseBool(true_indices=[0], total_indices=3)
Vec.SparseBool(true_indices=[1], total_indices=3)
Vec.SparseBool(true_indices=[1], total_indices=3)
Vec.SparseBool(true_indices=[2], total_indices=3)
Vec.SparseBool(true_indices=[0], total_indices=3)
Vec.SparseBool(true_indices=[1], total_indices=3)
Vec.SparseBool(true_indices=[0], total_indices=3)
Vec.SparseBool(true_indices=[2], total_indices=3)
```
It seems wrong because all of them have only 1 bit assigned.

**Comment by priamai** [comment]
Wait a minute the sparsebool are correct, those are just the positional indexes.
I am trying to understand now why there is an error during the writing phase.

**Comment by priamai** [comment]
okay I know what happened, the returned type here is a map not a list:

`vecs = utils.ndarray_to_sparse_bool_vectors(data_binary)`

so it is simply fixed via:

`(n_, errors) = eknn.index(index, vec_field, list(vecs), id_field, ids, refresh=True)`

Now testing with a larger matrix.

**Comment by alexklibisz** [comment]
> Wait a minute the sparsebool are correct, those are just the positional indexes.

Right - the sparse bool representation just contains the indices that are "true".

> okay I know what happened, the returned type here is a map not a list:

Hmm. Did this return type somehow change from the previous release? I had to make some numpy-related changes to get rid of some deprecation warnings.

**Comment by alexklibisz** [comment]
Ok, the changes are released here: https://github.com/alexklibisz/elastiknn/releases/tag/7.13.2.2

Thanks for your feedback.
