### ISSUE TITLE
LSH algorithm not working to me

### ISSUE THREAD

**Issue by minyoung90** [alexklibisz/elastiknn#290]
**Describe the bug**
I am not sure it is bug or not
my vector dimension is 768(using BERT), so I used lsh model for encoding.
Exact search is fine. it gives me collect answer at the top of result. (2.0 score)
but, when I queried using lsh, it gave me strange results.
the scores in that results are 0 to 0.1 all!
these scores are too low. is it right?

Here are what I tested parameter, with 6K test data. 

L = 200, 250
K = 7, 10

+ L=250, K=50 gives me a result with scores all 0!

**Expected behavior**
I think when I query using lsh, it gives me score over 1.0 at least.

**Environment (please complete the following information):**
 - Elastiknn version: 7.11.1
 - OS: ubutu 20.04 LTS

**To Reproduce**

**Additional context**

**Comment by minyoung90** [comment]
I noticed Permutation LSH seems working. with K = 400. but still can't get over 1.0 score.

**Comment by alexklibisz** [comment]
> K = 7, 10

> L=250, K=50 gives me a result with scores all 0!

Try lower values of k for Angular LSH. Like k=1 or k=2. 

The intuition behind L and k is this:
L is the number of hash tables. If you add more hash tables, it will take more time to search through them, but you're more likely to find a match for your query. So increasing L generally increases recall.
k is the number of bits in a hash. More bits makes the hash more "specific". This means you're less likely to match low-quality result, but you'll also match fewer results overall. So increasing k generally increases precision.

**Comment by minyoung90** [comment]
I tested with K = 1, and L = 99, 100, 250, 400 ...
what I found was that the query result scores with lsh were not closed enough over 1.89 (there is at least 3~5 data for that)
but, results were over 1.4~1.5.

**Comment by alexklibisz** [comment]
Interesting. Just as a sanity check, does exact search return the results that you expect? I'm guessing you are searching w/ one of the indexed vectors and expecting a score of 2?

**Comment by alexklibisz** [comment]
Closing this to keep things tidy. If you still have questions, please open a discussion: https://github.com/alexklibisz/elastiknn/discussions, as this seems more of a problem about finding proper hyperparameters than a bug.
