### ISSUE TITLE
Support multiple ES versions

### ISSUE THREAD

**Issue by dav009** [alexklibisz/elastiknn#314]
I am trying to have compatibility for some older ES versions (7.8.0). However I am encountering some issues.
I wonder whats the take in this project in the future regarding keeping support to older ES versions.

Sorry this is not a very specific request, but I wanted to kick off this conversation

**Comment by alexklibisz** [comment]
So, unfortunately this is a "wontfix". At least in terms of what I can do for the project right now.

I would be happy to review a PR that makes it possible to support multiple versions _without keeping parallel copies of the entire project for each version._ Maybe there's some very clever way to customize Gradle to do this. I tried for a few evenings last year and came up short. 

I'll go ahead and close this. Also noting that it's a duplicate of #120 and #238.
