### ISSUE TITLE
Elastiknn plugin size (possibly change JSON library to reduce dependency sizes)

### ISSUE THREAD

**Issue by fabriziofortino** [alexklibisz/elastiknn#316]
Starting from version 7.12.0.0, the plugin size went beyond 20MB (the previous version was 19.1MB).

Most Elastic cloud subscription levels have a hard limit of 20MB for custom plugins (see [here](https://www.elastic.co/guide/en/cloud/current/ec-custom-bundles.html#ec_before_you_begin_6)).

It would be great if the plugin could stay within this limit.

I had a quick look at the project and I think some heavy dependencies can be removed with little changes. An example would be guava, currently used for base64 encoding and simple caching logic. Replacing this with Java 8 code would remove ~3MB.

What do you think? If this sounds reasonable I can work on this.

**Comment by fabriziofortino** [comment]
Agree. Replacing the json library with borer seems to be the best thing to do to drastically reduce the plugin size.

I have anyway given a try updating the entire project to scala 2.13 and bump circe as well. Tests look okay except for `ExactSimilarityFunctionSuite`. I tried to dig in a bit but I am not sure why this does not work. Maybe you might want to have a look since it could be good to upgrade scala before changing the json library (see this branch https://github.com/fabriziofortino/elastiknn/tree/scala_2_13).

**Comment by alexklibisz** [comment]
Hi @fabriziofortino . That looks like excellent work. I appreciate you taking the time to do it. I'll try my best to look into the test issue this week, or on the weekend at the latest. I agree it's a good idea to go ahead with the scala update first.

**Comment by alexklibisz** [comment]
#317 LGTM. Unfortunately Github is having a hard time on the JVM tests. They all pass locally for me, so I'm not sure what is happening. Looking deeper ATM.

For the JSON library: I started looking deeper into Borer. I don't see much of an advantage of using Borer over just using the `elasticsearch-x-content` library, which contains `XContentBuilder` and `XContentParser`. This library is only ~150kb, so it's definitely small enough. Some reasons I'm thinking `elasticsearch-x-content` will be preferable:

1. It will reduce some serde overhead in the plugin itself. Currently there are several places where the plugin code takes an XContentParser, materializes it to a Map, turns that Map into a circe Json ADT, and then decodes the Json to a Scala type. We can avoid a lot of allocations my just going from XContentParser to the Scala type.
2. The current codec is already ~80% manual (i.e., uses the `HCursor`), and the API is stable. If the codec were largely derived or the API were rapidly evolving, I would see some advantage to learning another library's derivation quirks. However, in this case, we might as well just do the remaining 20% manually and avoid the overhead described in my previous point.

I took a first pass at a couple codecs here: https://github.com/alexklibisz/elastiknn/compare/elastiknn-316-xcontentcodec?expand=1

The main point is the `XContentCodec[T]` typeclass:

```scala
trait XContentCodec[T] {
  def buildUnsafe(t: T, x: XContentBuilder): Unit
  def parseUnsafe(p: XContentParser): T
}
```

My thinking right now is that this should replace the `ElasticsearchCodec`.

**Comment by alexklibisz** [comment]
Thanks. I changed the interfaces a bit (see the PR) since posting the comment, but still same idea. I'd like to add a couple abstractions for common patterns on the parsing side because that code is getting very tedious. Feel free to take a pass at it too if you're interested.

**Comment by alexklibisz** [comment]
Hey @fabriziofortino. I made some progress on this. When you get a chance, have a look at: https://github.com/alexklibisz/elastiknn/releases/tag/7.14.1.2-PR321-SNAPSHOT

The release artifact is down to 8MB.

![image](https://user-images.githubusercontent.com/8015228/142804250-2f6a9b71-6df6-49d3-b7dd-82bd012fd2a7.png)

I'd like to add a handful more tests for error scenarios over in #321.

**Comment by fabriziofortino** [comment]
Thanks @alexklibisz . That looks great! I will review the PR asap.

**Comment by alexklibisz** [comment]
Here's the new release: https://github.com/alexklibisz/elastiknn/releases/tag/7.14.1.3

Closing this now. Thanks for your help @fabriziofortino. Feel free to re-open if you find issues.
