### ISSUE TITLE
can't create a mapping

### ISSUE THREAD

**Issue by zsyu9779** [alexklibisz/elastiknn#530]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/alexklibisz/elastiknn/blob/main/readme.md#support)

### Background

when i create a mapping
PUT user_portrait
{
  "mappings": {
    "properties":{
    "user_id":{
      "type":"text"
    },
    "user_vec":{
      "type": "elastiknn_dense_float_vector",
      "dims":16,
      "model":"lsh",
      "similarity": "cosine",
      "L": 99,                          
      "k": 1 
    }
  }
  }
}

### Bug

{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "Failed to parse mapping [_doc]: Attempt to decode value on failed cursor: DownField(elastiknn)"
      }
    ],
    "type" : "mapper_parsing_exception",
    "reason" : "Failed to parse mapping [_doc]: Attempt to decode value on failed cursor: DownField(elastiknn)",
    "caused_by" : {
      "type" : "",
      "reason" : "Attempt to decode value on failed cursor: DownField(elastiknn)"
    }
  },
  "status" : 400
}

### Elastiknn Version

7.10.2.3

### Platform

my laptop

**Comment by alexklibisz** [comment]
﻿Please have another look at the docs. The dims, model, similarity, L and k properties should be nested inside of an object with key “elastiknn”.Sent from my iPhoneOn Jun 13, 2023, at 1:38 AM, zsyu9779 ***@***.***> wrote:﻿
Support guidelines

 I've read the support guidelines

Background
when i create a mapping
PUT user_portrait
{
"mappings": {
"properties":{
"user_id":{
"type":"text"
},
"user_vec":{
"type": "elastiknn_dense_float_vector",
"dims":16,
"model":"lsh",
"similarity": "cosine",
"L": 99,
"k": 1
}
}
}
}
Bug
{
"error" : {
"root_cause" : [
{
"type" : "mapper_parsing_exception",
"reason" : "Failed to parse mapping [_doc]: Attempt to decode value on failed cursor: DownField(elastiknn)"
}
],
"type" : "mapper_parsing_exception",
"reason" : "Failed to parse mapping [_doc]: Attempt to decode value on failed cursor: DownField(elastiknn)",
"caused_by" : {
"type" : "",
"reason" : "Attempt to decode value on failed cursor: DownField(elastiknn)"
}
},
"status" : 400
}
Elastiknn Version
7.10.2.3
Platform
my laptop
Steps to reproduce
No response
Additional info
No response
