### ISSUE TITLE
Hope to support version 7.17.20, later 7.17.x can be downloaded

### ISSUE THREAD

**Issue by liuxin638507** [alexklibisz/elastiknn#681]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/alexklibisz/elastiknn/blob/main/readme.md#support)

### Background

Hope to support version 7.17.20, later 7.17.x can be downloaded

### Bug

Hope to support version 7.17.20, later 7.17.x can be downloaded

### Elastiknn Version

Hope to support version 7.17.20, later 7.17.x can be downloaded

### Platform

Hope to support version 7.17.20, later 7.17.x can be downloaded

**Comment by alexklibisz** [comment]
Hi @liuxin638507, unfortunately I don't have the time to maintain elastiknn for both 7.x and 8.x. I recommend upgrading to 8.x.

If you can't do that, there's an old branch for 7.17.6: https://github.com/alexklibisz/elastiknn/tree/cross-build-7.17.6 Maybe you can fork that branch, and work through the updates to the latest 7.x version. The last commit on that branch was for 7.17.5 -> 7.17.6, so you should be able to use that as an example. You'll be missing some optimizations from recent work on 8.x.
